# Builder
FROM maven:3.9-eclipse-temurin-17-alpine as builder
RUN mkdir spring
WORKDIR spring

COPY pom.xml .
RUN mvn -B dependency:go-offline

# Runner!
FROM eclipse-temurin:17-jdk-alpine
VOLUME /tmp
LABEL version="0.1.2"
ENV version="0.1.2"
LABEL GAV="$(./mvnw help:evaluate -Dexpression=project.artifactId -q -DforceStdout)-$(./mvnw help:evaluate -Dexpression=project.version -q -DforceStdout)"
ENV GAV="$(./mvnw help:evaluate -Dexpression=project.artifactId -q -DforceStdout)-$(./mvnw help:evaluate -Dexpression=project.version -q -DforceStdout)"


COPY run.sh .
COPY target/data-0.1.3-SNAPSHOT.jar data-0.1.3-SNAPSHOT.jar

RUN chmod +x /run.sh


EXPOSE 8080

ENTRYPOINT ["/run.sh"]