amtrak:
    gtfs-url: https://content.amtrak.com/
    gtfs-uri: content/gtfs/GTFS.zip
    temp-file: ./data/tmp/gtfs.zip
    data-directory: ./data
    route-metadata: ./src/main/resources/metadata/route_stop_order.txt
    data-update-ms: 1000
logging:
    level:
        root: info
        com.wolginm.amtrak.data.handler.AmtrakDataHandler: debug
        com.wolginm.amtrak.data.service: debug