amtrak:
    route-metadata: ./src/main/resources/metadata/route_stop_order.txt
    gtfs:
        content_amtrak:     https://content.amtrak.com/
        uri_part:           content/gtfs/GTFS.zip
        tmp_dit:            ./tmp
        data_dictionary:    ./data