amtrak:
    retry-enabled: true
    route-metadata: ./src/main/resources/metadata/route_stop_order.txt
    gtfs:
        schema:             https
        host:               https://content.amtrak.com
        path:               /content/gtfs/GTFS.zip
        tmp-dir:            ./tmp
        data-dictionary:    ./data
        web-client:
            connectionTimeoutInMilliseconds: 60000
            responseTimeoutInMilliseconds: 60000
            readTimeoutInMilliseconds: 60000
            writeTimeoutInMilliseconds: 60000
        retry:
            maxRetryCount: 5
            delay: 1000
            maxDelay: 10000
            multiplier: 1.2
